name: Update Azure Local Endpoints

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'releases/**'
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate JSON files for Azure Local Endpoints
        shell: pwsh
        run: |
          Import-Module ('{0}\scripts\Export-AzureLocalEndpoints.ps1' -f $env:GITHUB_WORKSPACE) 
          $fileName = ($env:GITHUB_REPOSITORY -split '/')[-1]
          Export-AzureLocalEndpoints -FileName $fileName -IncludeDocumentation

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          message: "Auto updating required endpoints for Azure Local"
          add: "."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
